CREATE TABLE "tb_cliente" (
	"cpf_cliente" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"nome" VARCHAR(120) NOT NULL,
	"telefone" VARCHAR(30) NOT NULL,
	PRIMARY KEY("cpf_cliente")
);




CREATE TABLE "tb_carro" (
	"placa" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"modelo" VARCHAR(30) NOT NULL,
	"ano" DATE NOT NULL,
	"marca" VARCHAR(30) NOT NULL,
	"km" NUMERIC NOT NULL,
	PRIMARY KEY("placa")
);




CREATE TABLE "tb_aluguel" (
	"cod_aluguel" SERIAL NOT NULL UNIQUE,
	"dat_hr" TIMESTAMP NOT NULL,
	"fk_placa" INTEGER NOT NULL,
	"fk_cpf_cliente" BIGINT NOT NULL,
	PRIMARY KEY("cod_aluguel")
);



ALTER TABLE "tb_aluguel"
ADD FOREIGN KEY("fk_placa") REFERENCES "tb_carro"("placa")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "tb_aluguel"
ADD FOREIGN KEY("fk_cpf_cliente") REFERENCES "tb_cliente"("cpf_cliente")
ON UPDATE NO ACTION ON DELETE NO ACTION;
