CREATE TABLE "tb_pacientes" (
	"cpf_paciente" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"nome" VARCHAR(120) NOT NULL,
	"telefone" VARCHAR(30) NOT NULL,
	"endereco" VARCHAR(300) NOT NULL,
	PRIMARY KEY("cpf_paciente")
);




CREATE TABLE "tb_tipo_exames" (
	"cod_exame" SERIAL NOT NULL UNIQUE,
	"preco" NUMERIC(10,2) NOT NULL,
	"descricao" VARCHAR(100) NOT NULL,
	PRIMARY KEY("cod_exame")
);




CREATE TABLE "tb_medicos" (
	"crm" INTEGER NOT NULL UNIQUE,
	"nome" VARCHAR(120) NOT NULL,
	"especialidades" VARCHAR(200) NOT NULL,
	PRIMARY KEY("crm")
);




CREATE TABLE "tb_agendamentos" (
	"cod_aged" SERIAL NOT NULL UNIQUE,
	"data_aged" DATE NOT NULL,
	"hora_aged" TIME NOT NULL UNIQUE,
	"dat_hr_inclusao" TIMESTAMP NOT NULL,
	"fk_crm" INTEGER NOT NULL,
	"fk_cpf_paciente" BIGINT NOT NULL,
	"fk_cod_exame" SERIAL NOT NULL,
	PRIMARY KEY("cod_aged")
);



ALTER TABLE "tb_agendamentos"
ADD FOREIGN KEY("fk_crm") REFERENCES "tb_medicos"("crm")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "tb_agendamentos"
ADD FOREIGN KEY("fk_cpf_paciente") REFERENCES "tb_pacientes"("cpf_paciente")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "tb_agendamentos"
ADD FOREIGN KEY("fk_cod_exame") REFERENCES "tb_tipo_exames"("cod_exame")
ON UPDATE NO ACTION ON DELETE NO ACTION;