CREATE TABLE "tb_turmas" (
	"cod_turma" SERIAL NOT NULL UNIQUE,
	"descricao" VARCHAR(30) NOT NULL,
	PRIMARY KEY("cod_turma")
);




CREATE TABLE "tb_cusos" (
	"cod_curso" SERIAL NOT NULL UNIQUE,
	"duracao" SMALLINT NOT NULL,
	"area" VARCHAR(30) NOT NULL,
	"descricao" VARCHAR(30) NOT NULL,
	PRIMARY KEY("cod_curso")
);




CREATE TABLE "tb_estudantes" (
	"cpf" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"matricula" SERIAL NOT NULL,
	"nome" VARCHAR(120) NOT NULL,
	"email" VARCHAR(30) NOT NULL,
	"data_nascimento" DATE NOT NULL,
	"responsavel" VARCHAR(120) NOT NULL,
	"tel-responavel" VARCHAR(20) NOT NULL,
	"fk_cod_turma" INTEGER,
	"fk_cod_curso" INTEGER NOT NULL,
	PRIMARY KEY("cpf")
);



ALTER TABLE "tb_estudantes"
ADD FOREIGN KEY("fk_cod_turma") REFERENCES "tb_turmas"("cod_turma")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "tb_estudantes"
ADD FOREIGN KEY("fk_cod_curso") REFERENCES "tb_cusos"("cod_curso")
ON UPDATE NO ACTION ON DELETE NO ACTION;
